server.port: 8788
spring.cloud.stream.bindings:
  process-in-0:
    destination: salestransports
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9092
  serdeError: logAndContinue
  configuration:
    commit.interval.ms: 500
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
    spring.json.value.default.type: CSCI318.shareddomain.events.SalesTransportEvent